"""Type stubs for libdyson."""

from typing import Any

class DysonDevice:
    is_connected: bool
    is_on: bool
    auto_mode: bool | None
    speed: int | None
    oscillation: bool | None
    oscillation_angle_low: int | None
    oscillation_angle_high: int | None
    night_mode: bool | None
    heat_mode_is_on: bool | None
    heat_target: int | None
    temperature: int | None
    humidity: int | None

    def connect(self, host: str) -> None: ...
    def disconnect(self) -> None: ...
    def turn_on(self) -> None: ...
    def turn_off(self) -> None: ...
    def enable_auto_mode(self) -> None: ...
    def disable_auto_mode(self) -> None: ...
    def set_speed(self, speed: int) -> None: ...
    def enable_oscillation(self, angle_low: int = ..., angle_high: int = ...) -> None: ...
    def disable_oscillation(self) -> None: ...
    def enable_night_mode(self) -> None: ...
    def disable_night_mode(self) -> None: ...
    def enable_heat_mode(self) -> None: ...
    def disable_heat_mode(self) -> None: ...
    def set_heat_target(self, temperature: int) -> None: ...

def get_device(serial: str, credential: str, product_type: str) -> DysonDevice: ...

DEVICE_TYPE_PURE_HOT_COOL: str
DEVICE_TYPE_PURE_HOT_COOL_LINK: str
